### ISSUE TITLE
사용자 가입 스크린

### ISSUE THREAD

**Issue by wjaykim** [osamhack2021/web_app_LOCA_DimiTiger#9]
## Description
관리자에 의해 추가된 사용자 정보를 이용해 사용자가 서비스에 가입하는 모바일 앱 스크린 구현

### Required Feature
- 관리자가 제공하는 가입 정보 및 기타 사용자 정보를 기입하여 서비스에 가입
    - 군번
    - 이름
    - 가입 비밀번호
    - 전화번호
    - 이메일
    - 사용자 비밀번호

## TODO
- [ ] 애플리케이션 스크린 디자인
- [ ] 애플리케이션 기능 구현
- [x] Backend API 구현
